project:
  type: book
  output-dir: docs

book:
  title: "PFC develop"
  author: "Hu Zheng"
  date: "2025/12/01"
  date-format: YYYY-MM-DD
  chapters:
    - index.qmd
    
    - part: "Main Figure"
      chapters:
        - Figure1.qmd
        - Figure2.qmd
        - Figure3.qmd
        - Figure4.qmd
        - Figure5.qmd
        - Figure6.qmd

    - part: "Supplemental Figure"
      chapters:
        - Figure-S1.qmd
        - Figure-S2.qmd
        - Figure-S3.qmd
        - Figure-S4.qmd
        - Figure-S5.qmd
        - Figure-S6.qmd
        - Figure-S7.qmd

format:
  html:
    theme: cosmo
    code-fold: true
    code-tools: true



